Rationale for spare cids
tlswg/dtls13-spec pull request #185
Opened 2020-12-07 15:09 UTC by ekr

2020-12-08 00:20 UTC, martinthomson approved these changes

2020-12-10 15:07 UTC, chris-wood requested changes

2020-12-10 15:07 UTC, chris-wood commented on draft-ietf-tls-dtls13.md
> +path and thus attempt to have enough spare CIDs available to do so.
This confuses me. Presumably this is trying to say, "implementations should use a new CID for new paths, and should also request new CIDs if they anticipate path changes," or something. 

```suggestion
general, implementations SHOULD use a new CID whenever sending on a new path,
and SHOULD request new CIDs for this purpose if path changes are anticipated.
```

2020-12-13 02:10 UTC, kaduk commented on draft-ietf-tls-dtls13.md
> +If the client and server have negotiated using the "connection_id" extension,
```suggestion
If the client and server have negotiated use of the "connection_id" extension,
```

2020-12-20 10:43 UTC, hannestschofenig commented on draft-ietf-tls-dtls13.md
> +If the client and server have negotiated using the "connection_id" extension,
```suggestion
If the client and server have negotiated the use of CIDs with the "connection_id" extension,
```

2020-12-20 10:43 UTC, hannestschofenig commented
The proposed text sounds reasonable to me.

2021-01-04 19:52 UTC, chris-wood approved these changes

2021-01-20 13:33 UTC, merged